import {
  NumberFieldError,
  RequiredFieldError,
  StringFieldError,
  UnsupportedFieldError,
  AutoGeneratedFieldError,
} from "../errors";
import { Booking } from "../types/booking";

type BookingField = keyof Booking;
type ValidationFunction = (field: BookingField, value: any) => void;

const requiredFields: BookingField[] = [
  "clientId",
  "workerId",
  "subserviceId",
  "dateTime",
  "ratePerUnit",
  "unit",
  "status",
  "location",
];

const autoGeneratedFields: BookingField[] = [
  "id",
  "locationName",
  "serviceName",
  "subserviceName",
  "clientName",
  "workerName",
  "serviceAvatar",
  "timestamps",
];

const supportedFields: BookingField[] = [
  ...requiredFields,
  ...autoGeneratedFields,
];

const validateTypes: ValidationFunction = (field, value) => {
  // Type validity checks
  switch (field) {
    case "clientId":
    case "workerId":
    case "subserviceId":
    case "unit":
      if (typeof value !== "string") {
        throw new StringFieldError(field);
      }
      break;

    case "ratePerUnit":
      if (typeof value !== "number") {
        throw new NumberFieldError(field);
      }
      break;

    case "status":
      if (!["Pending", "Completed", "Not Completed"].includes(value)) {
        throw new Error(
          `Field '${field}' must be either "Pending", "Completed", or "Not Completed".`
        );
      }
      break;

    case "location":
      if (
        typeof value !== "object" ||
        typeof value?.latitude !== "number" ||
        typeof value?.longitude !== "number"
      ) {
        throw new Error(
          `Field '${field}' must be an object with latitude and longitude as numbers.`
        );
      }
      break;

    case "dateTime":
      if (
        typeof value !== "string" ||
        typeof value !== "number" ||
        isNaN(new Date(value).getTime())
      ) {
        throw new Error(
          `Field '${field}' must be either a string or a number which represents date and time.`
        );
      }
      break;
  }
};

export const validateBooking = (bookingData: Partial<Booking>): void => {
  // Check for missing required fields
  requiredFields.forEach((field) => {
    if (!bookingData[field]?.toString()) {
      throw new RequiredFieldError(field);
    }
  });

  validateBookingUpdate(bookingData);
};

export const validateBookingUpdate = (bookingData: Partial<Booking>): void => {
  Object.keys(bookingData).forEach((field) => {
    // Check for unsupported fields
    if (!supportedFields.includes(field as BookingField)) {
      throw new UnsupportedFieldError(field);
    }

    // Check for auto-generated fields
    if (autoGeneratedFields.includes(field as BookingField)) {
      throw new AutoGeneratedFieldError(field);
    }

    validateTypes(field as BookingField, bookingData[field as BookingField]);
  });
};
